package view;

import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JMenuBar;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JViewport;

public class MainView {
	
	JFrame frame;
	JButton translate;
	JTextArea cafeText ;
	JTextArea athenaText ;
	
	JPanel mainp = new JPanel();
	JPanel textP = new JPanel();
	JScrollPane leftp ;
	JScrollPane rightp ;
	JMenuBar menu;
	
	public MainView(JFrame callerFrame, JButton translate, JTextArea cafe, JMenuBar mbar){
		frame = callerFrame;
		this.translate = translate;
		cafeText = cafe;
		athenaText = new JTextArea("AutoGenerated JML Specification");
		leftp = new JScrollPane(cafeText);
		rightp = new JScrollPane(athenaText);
		menu = mbar;
	}
	
	
	
	public void buildView(){
		
		JPanel topp = new JPanel();
		
		BoxLayout mBox = new BoxLayout(mainp,  BoxLayout.Y_AXIS);
		mainp.setLayout(mBox);
		
		BoxLayout tBox = new BoxLayout(textP,BoxLayout.X_AXIS);
		textP.setLayout(tBox);
		
		textP.add(leftp);
		textP.add(rightp);
		topp.add(translate);
		
		mainp.add(textP);
		mainp.add(topp);
		
		frame.setJMenuBar(menu);
		mainp.revalidate();
		mainp.repaint();
		
		frame.setContentPane(mainp);
	}//end of buildView
	
	
	/**
	 * 
	 * @param text
	 * @param location if true then the right pane of the text panes will be updated
	 * else the left one
	 */
	public void updateView(JTextArea text, boolean location){
		//frame.removeAll();
		
		if(location){
			textP.remove(rightp);
			rightp = new JScrollPane(text);
			textP.add(rightp);
		}else{
			textP.removeAll();
			//leftp.set(frame.ge);
			leftp = new JScrollPane(text);
			textP.add(leftp);
			textP.add(rightp);
		}
		
		
		textP.revalidate();
		textP.repaint();
		
		mainp.revalidate();
		mainp.repaint();
		
		frame.setContentPane(mainp);
	}//end of buildView
	
	
	
	/**
	 * 
	 * @param location
	 * @return if location? it returns the JTextarea of the translation
	 * else the JTextArea of the CafeOBJ code is returned
	 */
	public JTextArea getTextArea(boolean location){
		JViewport viewport;
		if(location){
			viewport = rightp.getViewport();
			
		}else{
			viewport = leftp.getViewport();
		}
		return (JTextArea)viewport.getView();
	}//end of getTextArea
	
	
	
	
	
	
	

}
